version: "3.3"

#NETWORK
networks:
  net:
    driver: bridge

#IMAGES
services:
  front:
    container_name: front
    build: ./front
    ports:
      - "3002:3002"
    networks:
      - net
    env_file:
      - .env
    volumes:
      - ./front/src:/app/src
      - ./front/static:/app/static
      - node_modules_front:/app/node_modules
    depends_on:
      - back
  back:
    container_name: back 
    build: ./back
    volumes:
      - ./back:/usr/src/app
      - node_modules_back:/usr/src/app/node_modules
    ports:
      - 3000:3000
      - 3001:3001
    env_file:
      - .env
    networks:
      - net 
    depends_on:
      - bd 
  bd:
    container_name: "bd"
    image: postgres:14.5
    env_file:
      - .env
    networks:
      - net
    volumes:
      #- ./bd:/var/lib/postgresql/data 
      - volume_bd:/var/lib/postgresql/data 
    #ports:
      #- "5432:5432"
volumes:
  volume_bd:
  node_modules_front:
  node_modules_back: