version: "3.7"

#NETWORK
networks:
  net:
    driver: bridge

#IMAGES
services:
  front:
    container_name: front
    build: ./front
    ports:
      - "3001:3001"
    networks:
      - net
    env_file:
      - .env
    volumes:
      - ./front/src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - back
  back:
    container_name: back 
    build: ./back
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - net 
    depends_on:
      - bd 
  bd:
    container_name: "bd"
    image: postgres
    env_file:
      - .env
    networks:
      - net
    volumes:
      - ./bd:/var/lib/postgresql/data 
    ports:
      - "5432:5432"