version: "3.7"

#NETWORK
networks:
  net:
    driver: bridge

#IMAGES
services:
  back:
    container_name: back 
    build:
      context: ./back
      target: development
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - net 
    depends_on:
      - bd 
  bd:
    image: postgres
    environment:
      - .env
    networks:
      - net
    volumes:
      - /home/abittel/data/postgres:/var/lib/postgresql/data 
    ports:
      - "5432:5432"